name: GoTests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-go:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.8
      - uses: actions/checkout@v4.2.2
      - name: Make Gen
        run: make --output-sync -B gen
      - name: Check for unstaged files
        run: ./scripts/check_unstaged.sh